#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_news_index:
    path: /news
    controller: App\Controller\NewsTestController::createNews
app_news_show:
    path: /show/{id}
    controller: App\Controller\NewsTestController::show
app_form_show:
    path: /formulaire
    controller: App\Controller\NewsTestController::formulaire
app_form_Entry:
    path: /entryFormulaire
    controller:  App\Controller\NewsTestController::entryFormulaire
app_form_Out:
    path: /outFormulaire
    controller: App\Controller\NewsTestController::outFormulaire