#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number
app_news_index:
    path: /news
    controller: App\Controller\News\NewsController::createNews
app_news_show:
    path: /showNews/{id}
    controller: App\Controller\News\NewsController::show
app_form_show:
    path: /formulaireNews
    controller: App\Controller\News\NewsController::formulaire
app_form_Entry:
    path: /entryFormulaireNews
    controller:  App\Controller\News\NewsController::entryFormulaire
app_form_Out:
    path: /outFormulaireNews
    controller: App\Controller\News\NewsController::outFormulaire
app_comments_index:
    path: /comments
    controller: App\Controller\Comments\CommentsController::createNews
app_comments_show:
    path: /showComments/{id}
    controller: App\Controller\Comments\CommentsController::show
app_formComments_show:
    path: /formulaireComments
    controller: App\Controller\Comments\CommentsController::formulaire
app_formComments_Entry:
    path: /entryFormulaireComments
    controller:  App\Controller\Comments\CommentsController::entryFormulaire
app_formComments_Out:
    path: /outFormulaireComments
    controller: App\Controller\Comments\CommentsController::outFormulaire